package com.PetCaretopia.Notification;

public enum NotificationType {
    POST_SHARED,
    COMMENT_RECEIVED,
    POST_LIKED,
    APPOINTMENT_REQUESTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    PROFILE_UPDATED,
    SERVICE_PROVIDER_REQUESTED,
    GENERAL_ANNOUNCEMENT
}
